# New Relic Infrastructure - Kafka Integration Configuration
# This file configures nri-kafka to collect metrics from local Kafka instances
#
# Place this file at: /etc/newrelic-infra/integrations.d/kafka-config.yml

integrations:
  - name: nri-kafka
    env:
      # Cluster name - will be used in entity naming
      CLUSTER_NAME: "local-kafka-cluster"
      
      # Kafka version
      KAFKA_VERSION: "2.6.0"
      
      # Discovery strategy - can be "zookeeper" or "bootstrap"
      AUTODISCOVER_STRATEGY: "zookeeper"
      
      # Zookeeper connection for discovery
      ZOOKEEPER_HOSTS: '[{"host": "localhost", "port": 2181}]'
      
      # Alternative: Bootstrap discovery (comment out zookeeper above)
      # AUTODISCOVER_STRATEGY: "bootstrap"
      # BOOTSTRAP_BROKER_HOST: "localhost"
      # BOOTSTRAP_BROKER_KAFKA_PORT: 9092
      # BOOTSTRAP_BROKER_JMX_PORT: 9999
      
      # JMX settings
      COLLECT_BROKER_TOPIC_DATA: true
      
      # Topic configuration
      TOPIC_MODE: "all"  # or "none" or "list"
      # TOPIC_LIST: '["events", "orders", "inventory"]'  # If using "list" mode
      
      # Collect topic size (requires admin access)
      COLLECT_TOPIC_SIZE: true
      
      # Consumer group monitoring
      CONSUMER_GROUPS: '[{"name": "my-consumer-group", "topics": ["events"]}]'
      
      # Labels for filtering
      LABELS:
        env: "development"
        team: "platform"
        
    # How often to collect metrics
    interval: 30s

  # For monitoring multiple clusters, add additional entries:
  # - name: nri-kafka
  #   env:
  #     CLUSTER_NAME: "production-kafka"
  #     BOOTSTRAP_BROKER_HOST: "kafka-prod.example.com"
  #     # ... other settings
  #   interval: 60s