apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: producer-user
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: production-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
        operations:
          - Write
          - Create
          - Describe
      - resource:
          type: group
          name: "*"
        operations:
          - Read
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: consumer-user
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: production-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
        operations:
          - Read
          - Describe
      - resource:
          type: group
          name: "*"
        operations:
          - Read
          - Describe
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin-user
  namespace: strimzi-kafka
  labels:
    strimzi.io/cluster: production-kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
        operations:
          - All
      - resource:
          type: group
          name: "*"
        operations:
          - All
      - resource:
          type: cluster
        operations:
          - All