apiVersion: v1
kind: Secret
metadata:
  name: kafka-jmx-secret
  namespace: newrelic
type: Opaque
stringData:
  username: "cluster-operator"
  password: "PLACEHOLDER_PASSWORD"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-strimzi-config
  namespace: newrelic
data:
  nri-kafka-config.yml: |
    integrations:
      - name: nri-kafka
        command: nri-kafka
        env:
          CLUSTER_NAME: strimzi-production-kafka
          
          # Use bootstrap discovery for KRaft
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: production-kafka-kafka-bootstrap.strimzi-kafka.svc.cluster.local
          BOOTSTRAP_BROKER_KAFKA_PORT: 9092
          BOOTSTRAP_BROKER_JMX_PORT: 9999
          
          # JMX configuration for Strimzi
          DEFAULT_JMX_PORT: "9999"
          # DEFAULT_JMX_USER: "cluster-operator"
          # DEFAULT_JMX_PASSWORD: "${JMX_PASSWORD}"
          
          # TLS settings for JMX (disabled for now)
          # TLS_CA_FILE: "/var/run/secrets/jmx/ca.crt"
          # KEY_STORE: "/var/run/secrets/jmx/keystore.jks"
          # KEY_STORE_PASSWORD: "${KEYSTORE_PASSWORD}"
          # TRUST_STORE: "/var/run/secrets/jmx/truststore.jks"
          # TRUST_STORE_PASSWORD: "${TRUSTSTORE_PASSWORD}"
          
          # Collection settings
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          
          # Consumer settings
          CONSUMER_FETCH_OFFSET: "true"
          CONSUMER_GROUP_REGEX: ".*"
          
          # Topic settings
          TOPIC_MODE: all
          TOPIC_REGEX: ".*"
          COLLECT_TOPIC_SIZE: "true"
          COLLECT_TOPIC_OFFSET: "true"
          
          # Producer/Consumer JMX
          PRODUCERS: '[]'
          CONSUMERS: '[]'
          
          # Logging
          VERBOSE: "true"
          NRJMX_VERBOSE: "true"
        interval: 30s
        labels:
          env: kubernetes
          cluster: strimzi-kafka
          operator: strimzi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nri-kafka-strimzi
  namespace: newrelic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nri-kafka-strimzi
  template:
    metadata:
      labels:
        app: nri-kafka-strimzi
    spec:
      serviceAccountName: nri-bundle-newrelic-infrastructure
      containers:
      - name: nri-kafka
        image: newrelic/infrastructure:latest
        env:
        - name: NRIA_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: nri-bundle-newrelic-infrastructure-license
              key: licenseKey
        - name: NRIA_VERBOSE
          value: "1"
        - name: NRIA_LOG_LEVEL
          value: "debug"
        - name: NRIA_CUSTOM_ATTRIBUTES
          value: |
            {"clusterName":"strimzi-production-kafka","integration":"kafka","deployment":"strimzi","operator":"true"}
        - name: JMX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-jmx-secret
              key: password
        - name: KEYSTORE_PASSWORD
          value: "changeit"
        - name: TRUSTSTORE_PASSWORD
          value: "changeit"
        volumeMounts:
        - name: nri-kafka-config
          mountPath: /etc/newrelic-infra/integrations.d/
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: nri-kafka-config
        configMap:
          name: nri-kafka-strimzi-config