apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-config
  namespace: newrelic
data:
  kafka-config.yml: |
    integrations:
      - name: nri-kafka
        env:
          CLUSTER_NAME: strimzi-production-kafka
          
          # Use bootstrap discovery for KRaft
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: production-kafka-kafka-bootstrap.strimzi-kafka.svc.cluster.local
          BOOTSTRAP_BROKER_KAFKA_PORT: 9092
          BOOTSTRAP_BROKER_JMX_PORT: 9999
          
          # JMX configuration
          DEFAULT_JMX_PORT: "9999"
          
          # Collection settings
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          
          # Consumer settings
          CONSUMER_FETCH_OFFSET: "true"
          CONSUMER_GROUP_REGEX: ".*"
          
          # Topic settings
          TOPIC_MODE: all
          TOPIC_REGEX: ".*"
          COLLECT_TOPIC_SIZE: "true"
          COLLECT_TOPIC_OFFSET: "true"
        labels:
          env: kubernetes
          cluster: strimzi-kafka
          operator: strimzi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nri-kafka
  namespace: newrelic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nri-kafka
  template:
    metadata:
      labels:
        app: nri-kafka
    spec:
      serviceAccountName: nri-bundle-newrelic-infrastructure
      containers:
      - name: nri-kafka
        image: newrelic/infrastructure-bundle:latest
        command: ["/var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka"]
        env:
        - name: NRIA_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: nri-bundle-newrelic-infrastructure-license
              key: licenseKey
        - name: NRIA_VERBOSE
          value: "1"
        - name: CLUSTER_NAME
          value: "strimzi-production-kafka"
        - name: AUTODISCOVER_STRATEGY
          value: "bootstrap"
        - name: BOOTSTRAP_BROKER_HOST
          value: "production-kafka-kafka-bootstrap.strimzi-kafka.svc.cluster.local"
        - name: BOOTSTRAP_BROKER_KAFKA_PORT
          value: "9092"
        - name: BOOTSTRAP_BROKER_JMX_PORT
          value: "9999"
        - name: DEFAULT_JMX_PORT
          value: "9999"
        # JMX authentication disabled
        # - name: DEFAULT_JMX_USER
        #   value: "cluster-operator"
        # - name: DEFAULT_JMX_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: kafka-jmx-secret
        #       key: password
        - name: METRICS
          value: "true"
        - name: INVENTORY
          value: "true"
        - name: CONSUMER_FETCH_OFFSET
          value: "true"
        - name: TOPIC_MODE
          value: "all"
        - name: COLLECT_TOPIC_SIZE
          value: "true"
        - name: COLLECT_TOPIC_OFFSET
          value: "true"
        - name: NRJMX_VERBOSE
          value: "true"
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 256Mi