apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-config
  namespace: strimzi-kafka
data:
  jmx.properties: |
    com.sun.management.jmxremote=true
    com.sun.management.jmxremote.port=9999
    com.sun.management.jmxremote.rmi.port=9999
    com.sun.management.jmxremote.authenticate=false
    com.sun.management.jmxremote.ssl=false
    com.sun.management.jmxremote.local.only=false
    java.rmi.server.hostname=0.0.0.0
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: production-kafka
  namespace: strimzi-kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # Kafka broker configuration
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      # Performance tuning
      num.network.threads: 8
      num.io.threads: 8
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      # Log configuration
      log.retention.hours: 168
      log.segment.bytes: 1073741824
      log.retention.check.interval.ms: 300000
      # Enable auto topic creation
      auto.create.topics.enable: true
      delete.topic.enable: true
    authorization:
      type: simple
      superUsers:
        - cluster-operator
    # Disable JMX authentication
    jmxOptions: {}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    # JVM options to disable JMX authentication
    jvmOptions:
      -Xms: 1536m
      -Xmx: 1536m
      gcLoggingEnabled: true
      javaSystemProperties:
        - name: com.sun.management.jmxremote
          value: "true"
        - name: com.sun.management.jmxremote.authenticate
          value: "false"
        - name: com.sun.management.jmxremote.ssl
          value: "false"
        - name: com.sun.management.jmxremote.port
          value: "9999"
        - name: com.sun.management.jmxremote.rmi.port
          value: "9999"
        - name: java.rmi.server.hostname
          value: "0.0.0.0"
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "200m"
        limits:
          memory: 1Gi
          cpu: "500m"
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "200m"
        limits:
          memory: 1Gi
          cpu: "500m"
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    resources:
      requests:
        memory: 128Mi
        cpu: "100m"
      limits:
        memory: 256Mi
        cpu: "500m"