apiVersion: v1
kind: ConfigMap
metadata:
  name: java-kafka-clients
  namespace: kafka
data:
  producer.properties: |
    bootstrap.servers=kafka-0.kafka-headless.kafka.svc.cluster.local:9092
    key.serializer=org.apache.kafka.common.serialization.StringSerializer
    value.serializer=org.apache.kafka.common.serialization.StringSerializer
    client.id=java-producer-1
    acks=all
    retries=3
  consumer.properties: |
    bootstrap.servers=kafka-0.kafka-headless.kafka.svc.cluster.local:9092
    key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
    group.id=java-consumer-group
    client.id=java-consumer-1
    auto.offset.reset=earliest
    enable.auto.commit=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-kafka-producer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-producer
  template:
    metadata:
      labels:
        app: java-kafka-producer
    spec:
      containers:
      - name: producer
        image: confluentinc/cp-kafka:7.7.2
        ports:
        - containerPort: 9995
          name: jmx
        env:
        - name: JMX_PORT
          value: "9995"
        - name: KAFKA_JMX_OPTS
          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9995 -Dcom.sun.management.jmxremote.rmi.port=9995 -Djava.rmi.server.hostname=0.0.0.0"
        command:
        - /bin/bash
        - -c
        - |
          echo "Starting Java Kafka Producer with JMX on port 9995"
          
          while true; do
            echo "Producing messages..."
            kafka-producer-perf-test --topic events \
              --num-records 1000 \
              --record-size 100 \
              --throughput 10 \
              --producer-props bootstrap.servers=kafka-0.kafka-headless.kafka.svc.cluster.local:9092 \
              client.id=java-producer-events
            
            kafka-producer-perf-test --topic metrics \
              --num-records 1000 \
              --record-size 100 \
              --throughput 10 \
              --producer-props bootstrap.servers=kafka-0.kafka-headless.kafka.svc.cluster.local:9092 \
              client.id=java-producer-metrics
            
            kafka-producer-perf-test --topic logs \
              --num-records 1000 \
              --record-size 100 \
              --throughput 10 \
              --producer-props bootstrap.servers=kafka-0.kafka-headless.kafka.svc.cluster.local:9092 \
              client.id=java-producer-logs
            
            echo "Batch complete, sleeping..."
            sleep 60
          done
        volumeMounts:
        - name: config
          mountPath: /etc/kafka
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: java-kafka-clients
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-kafka-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-kafka-consumer
  template:
    metadata:
      labels:
        app: java-kafka-consumer
    spec:
      containers:
      - name: consumer
        image: confluentinc/cp-kafka:7.7.2
        ports:
        - containerPort: 9996
          name: jmx
        env:
        - name: JMX_PORT
          value: "9996"
        - name: KAFKA_JMX_OPTS
          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9996 -Dcom.sun.management.jmxremote.rmi.port=9996 -Djava.rmi.server.hostname=0.0.0.0"
        command:
        - /bin/bash
        - -c
        - |
          echo "Starting Java Kafka Consumer with JMX on port 9996"
          sleep 30
          
          echo "Starting consumer performance test..."
          kafka-consumer-perf-test --topic events \
            --bootstrap-server kafka-0.kafka-headless.kafka.svc.cluster.local:9092 \
            --messages 10000 \
            --consumer.config /etc/kafka/consumer.properties &
          
          # Keep container running
          tail -f /dev/null
        volumeMounts:
        - name: config
          mountPath: /etc/kafka
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: java-kafka-clients