FROM newrelic/infrastructure-bundle:latest

# Copy our custom nri-kafka binary
COPY --from=newrelic/nri-kafka:msk-enabled-v4 /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka

# Set permissions
RUN chmod 755 /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka