# JMX Configuration for MSK Shim
# This file contains all JMX beans required for full MSK compatibility
#
# To use this configuration:
# 1. Copy to your Kafka broker's config directory
# 2. Set JMX_CONFIG_FILE environment variable to point to this file
# 3. Restart nri-kafka integration

jmx_metrics:
  # Broker Throughput Metrics (P0)
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=BytesRejectedPerSec"
    attributes:
      - "Count"
      - "OneMinuteRate"
  
  # Controller Metrics (P0)
  - object_name: "kafka.controller:type=KafkaController,name=ActiveControllerCount"
    attributes:
      - "Value"
  
  - object_name: "kafka.controller:type=KafkaController,name=GlobalPartitionCount"
    attributes:
      - "Value"
  
  - object_name: "kafka.controller:type=KafkaController,name=OfflinePartitionsCount"
    attributes:
      - "Value"
  
  # Replication Metrics (P0)
  - object_name: "kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions"
    attributes:
      - "Value"
  
  - object_name: "kafka.server:type=ReplicaManager,name=IsrShrinksPerSec"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  - object_name: "kafka.server:type=ReplicaManager,name=IsrExpandsPerSec"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  - object_name: "kafka.controller:type=ControllerStats,name=LeaderElectionRateAndTimeMs"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "Mean"
  
  - object_name: "kafka.controller:type=ControllerStats,name=UncleanLeaderElectionsPerSec"
    attributes:
      - "Count"
      - "OneMinuteRate"
  
  # Request Latency Metrics (P0) - Fetch Consumer
  - object_name: "kafka.network:type=RequestMetrics,name=LocalTimeMs,request=FetchConsumer"
    attributes:
      - "Mean"
      - "50thPercentile"
      - "99thPercentile"
      - "Max"
  
  - object_name: "kafka.network:type=RequestMetrics,name=RequestQueueTimeMs,request=FetchConsumer"
    attributes:
      - "Mean"
      - "50thPercentile"
      - "99thPercentile"
      - "Max"
  
  - object_name: "kafka.network:type=RequestMetrics,name=ResponseSendTimeMs,request=FetchConsumer"
    attributes:
      - "Mean"
      - "50thPercentile"
      - "99thPercentile"
      - "Max"
  
  - object_name: "kafka.network:type=RequestMetrics,name=TotalTimeMs,request=FetchConsumer"
    attributes:
      - "Mean"
      - "50thPercentile"
      - "99thPercentile"
      - "Max"
  
  # Request Latency Metrics (P0) - Produce
  - object_name: "kafka.network:type=RequestMetrics,name=LocalTimeMs,request=Produce"
    attributes:
      - "Mean"
      - "50thPercentile"
      - "99thPercentile"
      - "Max"
  
  - object_name: "kafka.network:type=RequestMetrics,name=RequestQueueTimeMs,request=Produce"
    attributes:
      - "Mean"
      - "50thPercentile"
      - "99thPercentile"
      - "Max"
  
  - object_name: "kafka.network:type=RequestMetrics,name=ResponseSendTimeMs,request=Produce"
    attributes:
      - "Mean"
      - "50thPercentile"
      - "99thPercentile"
      - "Max"
  
  - object_name: "kafka.network:type=RequestMetrics,name=TotalTimeMs,request=Produce"
    attributes:
      - "Mean"
      - "50thPercentile"
      - "99thPercentile"
      - "Max"
  
  # Handler Utilization Metrics (P1)
  - object_name: "kafka.server:type=KafkaRequestHandlerPool,name=RequestHandlerAvgIdlePercent"
    attributes:
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  - object_name: "kafka.network:type=SocketServer,name=NetworkProcessorAvgIdlePercent"
    attributes:
      - "Value"
  
  # Throttling Metrics (P1)
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=ProduceThrottleTimeMs"
    attributes:
      - "Mean"
      - "Max"
  
  - object_name: "kafka.server:type=KafkaRequestHandlerPool,name=ProduceThrottleTimeMs"
    attributes:
      - "Mean"
      - "Max"
  
  - object_name: "kafka.server:type=KafkaRequestHandlerPool,name=FetchThrottleTimeMs"
    attributes:
      - "Mean"
      - "Max"
  
  - object_name: "kafka.server:type=KafkaRequestHandlerPool,name=RequestThrottleTimeMs"
    attributes:
      - "Mean"
      - "Max"
  
  # Zookeeper Metrics (P2)
  - object_name: "kafka.server:type=ZooKeeperClientMetrics,name=ZooKeeperRequestLatencyMs"
    attributes:
      - "Mean"
      - "Max"
  
  # Topic-level Metrics (P0) - with wildcard for all topics
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=BytesInPerSec,topic=*"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec,topic=*"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec,topic=*"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=BytesRejectedPerSec,topic=*"
    attributes:
      - "Count"
      - "OneMinuteRate"
  
  # Partition Metrics
  - object_name: "kafka.server:type=ReplicaManager,name=PartitionCount"
    attributes:
      - "Value"
  
  - object_name: "kafka.server:type=ReplicaManager,name=LeaderCount"
    attributes:
      - "Value"
  
  # Request Rate Metrics
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=TotalFetchRequestsPerSec"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=TotalProduceRequestsPerSec"
    attributes:
      - "Count"
      - "OneMinuteRate"
      - "FiveMinuteRate"
      - "FifteenMinuteRate"
      - "MeanRate"
  
  # App Info for broker ID
  - object_name: "kafka.server:type=app-info"
    attributes:
      - "id"
      - "version"

# Additional configuration for V2 metrics (if ENABLE_BROKER_TOPIC_METRICS_V2 is true)
v2_jmx_metrics:
  # V2 Controller metrics
  - object_name: "kafka.controller:type=KafkaController,name=ActiveControllerCount"
    attributes:
      - "Value"
  
  - object_name: "kafka.controller:type=KafkaController,name=GlobalPartitionCount"
    attributes:
      - "Value"
  
  # V2 Topic-specific broker metrics
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=BytesOutPerSec,topic=*"
    attributes:
      - "Count"
      - "OneMinuteRate"
  
  - object_name: "kafka.server:type=BrokerTopicMetrics,name=MessagesInPerSec,topic=*"
    attributes:
      - "Count"
      - "OneMinuteRate"