integrations:
  - name: nri-kafka
    env:
      # Cluster identification
      CLUSTER_NAME: local-kafka-cluster
      
      # Discovery settings
      AUTODISCOVER_STRATEGY: bootstrap
      BOOTSTRAP_BROKER_HOST: localhost
      BOOTSTRAP_BROKER_KAFKA_PORT: 9092
      BOOTSTRAP_BROKER_JMX_PORT: 9999
      
      # Collection settings
      METRICS: "true"
      INVENTORY: "true"
      COLLECT_BROKER_TOPIC_DATA: "true"
      COLLECT_TOPIC_SIZE: "true"
      COLLECT_TOPIC_OFFSET: "true"
      TOPIC_MODE: "all"
      CONSUMER_OFFSET: "true"
      CONSUMER_GROUP_REGEX: ".*"
      
      # MSK Shim Configuration - CRITICAL FOR MSK UI
      MSK_SHIM_ENABLED: "true"
      MSK_USE_DIMENSIONAL: "true"  # This enables dimensional metrics for UI
      AWS_ACCOUNT_ID: "123456789012"
      AWS_REGION: "us-east-1"
      KAFKA_CLUSTER_NAME: "local-kafka-cluster"
      MSK_CLUSTER_ARN: "arn:aws:kafka:us-east-1:123456789012:cluster/local-kafka-cluster/12345678-1234-1234-1234-123456789012"
      ENVIRONMENT: "production"
      
      # Connection settings
      TIMEOUT: "30000"
      
      # Logging
      VERBOSE: "true"
      LOG_LEVEL: "debug"
      
    interval: 30s
    timeout: 30s
    inventory_source: config/kafka
    labels:
      env: production
      cluster: local-kafka-cluster
      integration: nri-kafka
      msk_enabled: "true"