apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-jmx
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-producer-jmx
  template:
    metadata:
      labels:
        app: kafka-producer-jmx
    spec:
      containers:
      - name: producer
        image: confluentinc/cp-kafka:latest
        env:
        - name: KAFKA_JMX_ENABLED
          value: "true"
        - name: KAFKA_JMX_PORT
          value: "9998"
        - name: KAFKA_JMX_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: JMX_PORT
          value: "9998"
        ports:
        - containerPort: 9998
          name: jmx
        command:
        - bash
        - -c
        - |
          export KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9998 -Dcom.sun.management.jmxremote.rmi.port=9998 -Djava.rmi.server.hostname=${KAFKA_JMX_HOSTNAME}"
          
          while true; do
            for i in {1..50}; do
              echo "Producer-JMX-Message-$i: {\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"producer\":\"jmx-producer\",\"value\":$((RANDOM % 1000))}" | \
                kafka-console-producer --bootstrap-server kafka-0.kafka-headless.kafka.svc.cluster.local:9092 --topic events
              sleep 0.2
            done
            sleep 10
          done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-jmx
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-consumer-jmx
  template:
    metadata:
      labels:
        app: kafka-consumer-jmx
    spec:
      containers:
      - name: consumer
        image: confluentinc/cp-kafka:latest
        env:
        - name: KAFKA_JMX_ENABLED
          value: "true"
        - name: KAFKA_JMX_PORT
          value: "9997"
        - name: KAFKA_JMX_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: JMX_PORT
          value: "9997"
        ports:
        - containerPort: 9997
          name: jmx
        command:
        - bash
        - -c
        - |
          export KAFKA_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9997 -Dcom.sun.management.jmxremote.rmi.port=9997 -Djava.rmi.server.hostname=${KAFKA_JMX_HOSTNAME}"
          
          while true; do
            timeout 30s kafka-console-consumer \
              --bootstrap-server kafka-0.kafka-headless.kafka.svc.cluster.local:9092 \
              --topic events \
              --group jmx-consumer-group \
              --from-beginning || true
            sleep 5
          done
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-jmx-service
  namespace: kafka
spec:
  selector:
    app: kafka-producer-jmx
  ports:
  - name: jmx
    port: 9998
    targetPort: 9998
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-jmx-service
  namespace: kafka
spec:
  selector:
    app: kafka-consumer-jmx
  ports:
  - name: jmx
    port: 9997
    targetPort: 9997
  clusterIP: None