# Kubernetes Secret for New Relic License Key
# 
# Usage:
# 1. Create this secret with your actual license key:
#    kubectl create secret generic newrelic-license --from-literal=license-key=YOUR_ACTUAL_LICENSE_KEY
# 
# Or use this file:
# 1. Replace YOUR_LICENSE_KEY_HERE with your actual license key
# 2. Apply: kubectl apply -f newrelic-secret.yaml
#
apiVersion: v1
kind: Secret
metadata:
  name: newrelic-license
  namespace: default
type: Opaque
stringData:
  license-key: YOUR_LICENSE_KEY_HERE  # Replace with your actual New Relic license key