# NRI-Kafka ConfigMap - Consolidated Configuration
# This configures both standard Kafka integration and MSK shim
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-config
  namespace: strimzi-kafka
data:
  kafka-config.yml: |
    ---
    integrations:
      - name: nri-kafka
        env:
          # Cluster identification
          CLUSTER_NAME: kafka-k8s-monitoring
          
          # Discovery strategy - using bootstrap for better reliability
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: production-kafka-kafka-bootstrap.strimzi-kafka.svc.cluster.local
          BOOTSTRAP_BROKER_KAFKA_PORT: 9092
          BOOTSTRAP_BROKER_JMX_PORT: 9999
          
          # JMX Configuration (no auth per Strimzi setup)
          JMX_USER: ""
          JMX_PASS: ""
          
          # Enable all collection types
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          
          # Topic collection - collect all topics
          COLLECT_BROKER_TOPIC_DATA: "true"
          COLLECT_TOPIC_SIZE: "true"
          COLLECT_TOPIC_OFFSET: "true"
          TOPIC_MODE: "all"
          TOPIC_LIST: '[]'
          TOPIC_REGEX: '[]'
          
          # Consumer group monitoring
          CONSUMER_OFFSET: "true"
          CONSUMER_GROUPS: '[]'  # Empty = all groups
          
          # Producer/Consumer monitoring
          PRODUCERS: '[]'  # Empty = all producers
          CONSUMERS: '[]'  # Empty = all consumers
          
          # Connection settings
          TIMEOUT: "30000"
          CONNECTION_TIMEOUT: "30000"
          
          # Performance tuning
          TOPIC_BUCKET_SIZE: "50"
          
          # Logging
          VERBOSE: "false"  # Set to true for debugging
          
        interval: 30s
        timeout: 30s
        inventory_source: config/kafka
        labels:
          env: kubernetes
          cluster: kafka-k8s-monitoring
          integration: nri-kafka
          version: "3.7.0"