# Standard NRI-Kafka Deployment
# Uses New Relic Infrastructure agent with Kafka integration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nri-kafka
  namespace: strimzi-kafka
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nri-kafka
rules:
- apiGroups: [""]
  resources:
    - nodes
    - nodes/metrics
    - nodes/stats
    - nodes/proxy
    - pods
    - services
    - endpoints
  verbs: ["get", "list"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nri-kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nri-kafka
subjects:
- kind: ServiceAccount
  name: nri-kafka
  namespace: strimzi-kafka
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nri-kafka
  namespace: strimzi-kafka
  labels:
    app: nri-kafka
spec:
  selector:
    matchLabels:
      app: nri-kafka
  template:
    metadata:
      labels:
        app: nri-kafka
    spec:
      serviceAccountName: nri-kafka
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: nri-kafka
        image: newrelic/infrastructure:latest
        env:
        # New Relic License Key
        - name: NRIA_LICENSE_KEY
          value: "dfb79449d23acce4df582f2f5550abe4FFFFNRAL"
        
        # Infrastructure agent configuration
        - name: NRIA_OVERRIDE_HOSTNAME_SHORT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        
        - name: NRIA_CUSTOM_ATTRIBUTES
          value: '{"clusterName":"kafka-k8s-monitoring","environment":"kubernetes","deployment":"standard"}'
        
        # Logging
        - name: NRIA_LOG_LEVEL
          value: "info"
        
        # Pass environment to integrations
        - name: NRIA_PASSTHROUGH_ENVIRONMENT
          value: "KUBERNETES_SERVICE_HOST,KUBERNETES_SERVICE_PORT,CLUSTER_NAME"
        
        # Disable infrastructure sampling to reduce overhead
        - name: DISABLE_KUBE_STATE_METRICS
          value: "true"
        
        volumeMounts:
        - name: config
          mountPath: /etc/newrelic-infra/integrations.d/
          readOnly: true
        - name: host-root
          mountPath: /host
          readOnly: true
        
        resources:
          requests:
            memory: "150Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "200m"
        
        securityContext:
          privileged: true
          
      volumes:
      - name: config
        configMap:
          name: nri-kafka-config
      - name: host-root
        hostPath:
          path: /