apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-comprehensive-traffic
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: traffic-generator
        image: confluentinc/cp-kafka:latest
        command:
        - bash
        - -c
        - |
          echo "🚀 Starting comprehensive Kafka traffic generation..."
          
          # Create multiple consumer groups
          for group in test-group-1 test-group-2 analytics-group monitoring-group; do
            echo "Starting consumer group: $group"
            timeout 120s kafka-console-consumer \
              --bootstrap-server kafka-0.kafka-headless.kafka.svc.cluster.local:9092 \
              --topic events \
              --group $group \
              --from-beginning &
              
            timeout 120s kafka-console-consumer \
              --bootstrap-server kafka-0.kafka-headless.kafka.svc.cluster.local:9092 \
              --topic metrics \
              --group $group \
              --from-beginning &
          done
          
          # Generate high-volume producer traffic
          for i in {1..200}; do
            # High-volume events
            for j in {1..10}; do
              echo "Event-$i-$j: {\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"user\":\"user$j\",\"action\":\"click\",\"value\":$((RANDOM % 100))}" | \
                kafka-console-producer --broker-list kafka-0.kafka-headless.kafka.svc.cluster.local:9092 --topic events
            done
            
            # Metrics data
            for j in {1..5}; do
              echo "Metric-$i-$j: {\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"metric\":\"cpu.usage\",\"host\":\"host$j\",\"value\":$((RANDOM % 100))}" | \
                kafka-console-producer --broker-list kafka-0.kafka-headless.kafka.svc.cluster.local:9092 --topic metrics
            done
            
            # Log data  
            echo "Log-$i: $(date -u +%Y-%m-%dT%H:%M:%SZ) INFO Application started successfully on host-$((RANDOM % 10))" | \
              kafka-console-producer --broker-list kafka-0.kafka-headless.kafka.svc.cluster.local:9092 --topic logs
              
            sleep 0.5
          done
          
          echo "✅ Traffic generation completed"
          sleep 60  # Keep consumers running
      restartPolicy: Never
  backoffLimit: 0