apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-debug-config
  namespace: kafka  # Adjust to your Kafka namespace
data:
  kafka-config.yml: |
    integrations:
    - name: nri-kafka
      env:
        VERBOSE: "true"
        CLUSTER_NAME: "strimzi-debug"
        KAFKA_VERSION: "2.8.0"
        
        # For sidecar deployment - connect to localhost
        AUTODISCOVER_STRATEGY: "bootstrap"
        BOOTSTRAP_BROKER_HOST: "localhost"
        BOOTSTRAP_BROKER_KAFKA_PORT: 9092
        BOOTSTRAP_BROKER_KAFKA_PROTOCOL: "PLAINTEXT"
        BOOTSTRAP_BROKER_JMX_PORT: 9999
        
        LOCAL_ONLY_COLLECTION: true
        TOPIC_MODE: "none"
        
        METRICS: "true"
        INVENTORY: "false"
        
        TIMEOUT: 30000
      interval: 30s

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nri-kafka-debug
  namespace: kafka  # Adjust to your Kafka namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nri-kafka-debug
  template:
    metadata:
      labels:
        app: nri-kafka-debug
    spec:
      serviceAccountName: default  # Adjust if needed
      containers:
      - name: nri-kafka
        image: newrelic/nri-kafka:latest  # Or your custom built image
        env:
        - name: NRIA_LICENSE_KEY
          value: "YOUR_LICENSE_KEY_HERE"
        - name: NRIA_VERBOSE
          value: "1"
        - name: NRIA_LOG_LEVEL
          value: "debug"
        # For testing, output to stdout
        - name: NRIA_METRICS_PROCESS_SAMPLE_RATE
          value: "30"
        command:
        - /bin/sh
        - -c
        - |
          echo "=== Starting NRI-Kafka Debug Pod ==="
          echo "Testing JMX connectivity..."
          
          # Test network connectivity
          nc -zv kafka-cluster-kafka-0.kafka-cluster-kafka-brokers 9092 || echo "Kafka port not reachable"
          nc -zv kafka-cluster-kafka-0.kafka-cluster-kafka-brokers 9999 || echo "JMX port not reachable"
          
          # Run the integration with debug output
          echo "Running integration..."
          /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka \
            -verbose \
            -pretty \
            -config_path /etc/nri-kafka/kafka-config.yml
          
          # Keep pod running for debugging
          sleep 3600
        volumeMounts:
        - name: config
          mountPath: /etc/nri-kafka
      volumes:
      - name: config
        configMap:
          name: nri-kafka-debug-config

---
# Alternative: Run as a sidecar in Kafka StatefulSet
# This example shows how to add nri-kafka as a sidecar container
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-exporter-config
  namespace: kafka
data:
  jmx-kafka-config.yml: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
    - pattern: ".*"

---
# Example patch for Strimzi Kafka StatefulSet to add nri-kafka sidecar
# Apply with: kubectl patch statefulset kafka-cluster-kafka -n kafka --patch-file this-file.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-cluster-kafka
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: nri-kafka-sidecar
        image: newrelic/nri-kafka:latest
        env:
        - name: NRIA_LICENSE_KEY
          value: "YOUR_LICENSE_KEY_HERE"
        - name: NRIA_VERBOSE
          value: "1"
        command:
        - /bin/sh
        - -c
        - |
          # Wait for Kafka to be ready
          sleep 30
          
          # Create config file
          cat > /tmp/kafka-config.yml << EOF
          integrations:
          - name: nri-kafka
            env:
              VERBOSE: "true"
              CLUSTER_NAME: "strimzi-sidecar"
              KAFKA_VERSION: "2.8.0"
              AUTODISCOVER_STRATEGY: "bootstrap"
              BOOTSTRAP_BROKER_HOST: "localhost"
              BOOTSTRAP_BROKER_KAFKA_PORT: 9092
              BOOTSTRAP_BROKER_KAFKA_PROTOCOL: "PLAINTEXT"
              BOOTSTRAP_BROKER_JMX_PORT: 9999
              LOCAL_ONLY_COLLECTION: true
              TOPIC_MODE: "none"
              METRICS: "true"
              INVENTORY: "false"
              TIMEOUT: 30000
            interval: 30s
          EOF
          
          # Run integration in a loop for debugging
          while true; do
            echo "=== Running NRI-Kafka at $(date) ==="
            /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka \
              -verbose \
              -pretty \
              -config_path /tmp/kafka-config.yml
            echo "=== Completed at $(date) ==="
            sleep 30
          done