apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-config-dual
  namespace: newrelic
data:
  nri-kafka-config.yml: |
    integrations:
      # Original Kafka Cluster (kafka namespace)
      - name: nri-kafka
        env:
          CLUSTER_NAME: minikube-kafka
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: kafka-0.kafka-headless.kafka.svc.cluster.local
          BOOTSTRAP_BROKER_KAFKA_PORT: 9092
          BOOTSTRAP_BROKER_JMX_PORT: 9999
          DEFAULT_JMX_PORT: 9999
          
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          
          COLLECT_BROKER_TOPIC_DATA: "true"
          COLLECT_TOPIC_SIZE: "true" 
          COLLECT_TOPIC_OFFSET: "true"
          TOPIC_MODE: "all"
          
          CONSUMER_OFFSET: "true"
          CONSUMER_GROUP_REGEX: ".*"
          
          TIMEOUT: "30000"
          
          # Producer and Consumer JMX endpoints
          PRODUCERS: '[{"host": "10.244.0.23", "port": 9998}, {"host": "10.244.0.22", "port": 9998}]'
          CONSUMERS: '[{"host": "10.244.0.21", "port": 9997}, {"host": "10.244.0.24", "port": 9997}]'
          
          # MSK Shim Configuration
          MSK_SHIM_ENABLED: "true"
          AWS_ACCOUNT_ID: "123456789012"  # Use proper 12-digit AWS account format
          AWS_REGION: "us-east-1"
          KAFKA_CLUSTER_NAME: "minikube-kafka"
          ENVIRONMENT: "minikube"
          
          # Logging
          VERBOSE: "true"
          LOG_LEVEL: "debug"
          
        interval: 30s
        timeout: 30s
        inventory_source: config/kafka
        labels:
          env: minikube
          cluster: minikube-kafka
          integration: nri-kafka
          msk_enabled: "true"
      
      # Strimzi Kafka Cluster (strimzi-kafka namespace)  
      - name: nri-kafka
        env:
          CLUSTER_NAME: strimzi-kafka-cluster
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: strimzi-kafka-cluster-kafka-bootstrap.strimzi-kafka.svc.cluster.local
          BOOTSTRAP_BROKER_KAFKA_PORT: 9092
          BOOTSTRAP_BROKER_JMX_PORT: 9999
          DEFAULT_JMX_PORT: 9999
          
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          
          COLLECT_BROKER_TOPIC_DATA: "true"
          COLLECT_TOPIC_SIZE: "true"
          COLLECT_TOPIC_OFFSET: "true"
          TOPIC_MODE: "all"
          
          CONSUMER_OFFSET: "true"
          CONSUMER_GROUP_REGEX: ".*"
          
          TIMEOUT: "30000"
          
          # MSK Shim Configuration
          MSK_SHIM_ENABLED: "true"
          AWS_ACCOUNT_ID: "123456789012"  # Use proper 12-digit AWS account format
          AWS_REGION: "us-west-2"
          KAFKA_CLUSTER_NAME: "strimzi-kafka-cluster"
          ENVIRONMENT: "minikube-strimzi"
          
          # Logging
          VERBOSE: "true"
          LOG_LEVEL: "debug"
          
        interval: 30s
        timeout: 30s
        inventory_source: config/kafka
        labels:
          env: minikube
          cluster: strimzi-kafka
          integration: nri-kafka
          msk_enabled: "true"