apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-config
  namespace: newrelic
data:
  kafka-config.yml: |
    ---
    integrations:
      # Monitor Kafka in kafka namespace
      - name: nri-kafka
        env:
          # Cluster identification
          CLUSTER_NAME: minikube-kafka
          
          # Discovery settings
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: kafka-0.kafka-headless.kafka.svc.cluster.local
          BOOTSTRAP_BROKER_KAFKA_PORT: 9092
          BOOTSTRAP_BROKER_JMX_PORT: 9999
          
          # JMX Configuration (no auth)
          JMX_USER: ""
          JMX_PASS: ""
          
          # Collection settings
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          
          # Topic collection
          COLLECT_BROKER_TOPIC_DATA: "true"
          COLLECT_TOPIC_SIZE: "true"
          COLLECT_TOPIC_OFFSET: "true"
          TOPIC_MODE: "all"
          TOPIC_LIST: '[]'
          
          # Consumer monitoring
          CONSUMER_OFFSET: "true"
          CONSUMER_GROUP_REGEX: '.*'  # Fixed: was CONSUMER_GROUPS_REGEX
          
          # Connection settings
          TIMEOUT: "30000"
          
          # MSK Shim Configuration - Always Enabled
          MSK_SHIM_ENABLED: "true"
          AWS_ACCOUNT_ID: "123456789012"
          AWS_REGION: "us-east-1"
          KAFKA_CLUSTER_NAME: "minikube-kafka"
          
          # Additional MSK settings
          ENVIRONMENT: "minikube"
          MSK_BATCH_SIZE: "100"
          MSK_FLUSH_INTERVAL: "5s"
          
          # Logging
          VERBOSE: "true"
          LOG_LEVEL: "debug"
          
          # Local only mode (for testing)
          LOCAL_ONLY_COLLECTION: "false"
          
        interval: 30s
        timeout: 30s
        inventory_source: config/kafka
        labels:
          env: minikube
          cluster: minikube-kafka
          integration: nri-kafka
          msk_enabled: "true"
      
      # Optional: Monitor Strimzi Kafka if deployed
      - name: nri-kafka
        env:
          # Cluster identification
          CLUSTER_NAME: minikube-strimzi-kafka
          
          # Discovery settings
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: minikube-kafka-kafka-bootstrap.strimzi-kafka.svc.cluster.local
          BOOTSTRAP_BROKER_KAFKA_PORT: 9092
          BOOTSTRAP_BROKER_JMX_PORT: 9999
          
          # JMX Configuration (Strimzi may have auth)
          JMX_USER: "admin"
          JMX_PASS: "admin123"
          
          # Collection settings
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          
          # Topic collection
          COLLECT_BROKER_TOPIC_DATA: "true"
          COLLECT_TOPIC_SIZE: "true"
          COLLECT_TOPIC_OFFSET: "true"
          TOPIC_MODE: "all"
          
          # Consumer monitoring
          CONSUMER_OFFSET: "true"
          CONSUMER_GROUP_REGEX: '.*'  # Fixed: was missing
          
          # Connection settings
          TIMEOUT: "30000"
          
          # MSK Shim Configuration
          MSK_SHIM_ENABLED: "true"
          AWS_ACCOUNT_ID: "123456789012"
          AWS_REGION: "us-west-2"
          KAFKA_CLUSTER_NAME: "minikube-strimzi-kafka"
          
          # Logging
          VERBOSE: "true"
          
        interval: 30s
        timeout: 30s
        inventory_source: config/kafka
        labels:
          env: minikube
          cluster: strimzi-kafka
          integration: nri-kafka
          msk_enabled: "true"