apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-config
  namespace: newrelic
data:
  nri-kafka-config.yml: |
    integrations:
      - name: nri-kafka
        env:
          CLUSTER_NAME: minikube-kafka
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: kafka-0.kafka-headless.kafka.svc.cluster.local
          BOOTSTRAP_BROKER_KAFKA_PORT: 9092
          BOOTSTRAP_BROKER_JMX_PORT: 9999
          DEFAULT_JMX_PORT: 9999
          METRICS: "true"
          INVENTORY: "true"
          COLLECT_BROKER_TOPIC_DATA: "true"
          COLLECT_TOPIC_SIZE: "true"
          COLLECT_TOPIC_OFFSET: "true"
          TOPIC_MODE: "all"
          CONSUMER_OFFSET: "true"
          CONSUMER_GROUP_REGEX: ".*"
          TIMEOUT: "30000"
          
          # Producer and Consumer collection
          PRODUCERS: '[{"host": "10.244.0.27", "port": 9995}]'
          CONSUMERS: '[{"host": "10.244.0.28", "port": 9996}]'
          DEFAULT_JMX_HOST: "localhost"
          DEFAULT_JMX_PORT: 9999
          
          # MSK Shim Configuration
          MSK_SHIM_ENABLED: "true"
          AWS_ACCOUNT_ID: "3630072"
          AWS_REGION: "us-east-1"
          KAFKA_CLUSTER_NAME: "minikube-kafka"
        interval: 30s
        timeout: 30s
        inventory_source: config/kafka
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nri-kafka-bundle
  namespace: newrelic
  labels:
    app: nri-kafka-bundle
spec:
  selector:
    matchLabels:
      app: nri-kafka-bundle
  template:
    metadata:
      labels:
        app: nri-kafka-bundle
    spec:
      serviceAccountName: nri-kafka
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: nri-kafka
        image: nri-kafka-msk-bundle:v1.2
        imagePullPolicy: Never
        securityContext:
          privileged: true
        env:
        - name: NRIA_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-credentials
              key: license-key
        - name: NRIA_VERBOSE
          value: "1"
        - name: NRIA_LOG_LEVEL
          value: "debug"
        - name: NRIA_OVERRIDE_HOSTNAME_SHORT
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NRIA_CUSTOM_ATTRIBUTES
          value: '{"clusterName":"minikube","environment":"development"}'
        - name: DISABLE_KUBE_STATE_METRICS
          value: "true"
        - name: NEW_RELIC_METADATA_KUBERNETES_CLUSTER_NAME
          value: "minikube"
        volumeMounts:
        - name: config
          mountPath: /etc/newrelic-infra/integrations.d/
        - name: host-docker-socket
          mountPath: /var/run/docker.sock
        - name: log
          mountPath: /var/log
        - name: host-volume
          mountPath: /host
          readOnly: true
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 150Mi
      volumes:
      - name: config
        configMap:
          name: nri-kafka-config
      - name: host-docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: log
        hostPath:
          path: /var/log
      - name: host-volume
        hostPath:
          path: /
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute