apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-config
  namespace: strimzi-kafka  # Update this to your namespace
data:
  kafka-config.yml: |
    ---
    integrations:
      - name: nri-kafka
        env:
          # Fixed cluster name to match .env file
          CLUSTER_NAME: kafka-k8s-monitoring
          
          # Auto-discovery using bootstrap
          AUTODISCOVER_STRATEGY: bootstrap
          
          # Bootstrap broker - Strimzi service
          BOOTSTRAP_BROKER_HOST: production-kafka-kafka-bootstrap.strimzi-kafka.svc.cluster.local
          BOOTSTRAP_BROKER_KAFKA_PORT: 9092
          BOOTSTRAP_BROKER_JMX_PORT: 9999
          
          # JMX Authentication (disabled based on monitoring status)
          JMX_USER: ""
          JMX_PASS: ""
          
          # Enable all collections
          COLLECT_BROKER_TOPIC_DATA: "true"
          COLLECT_TOPIC_SIZE: "true"
          COLLECT_TOPIC_OFFSET: "true"
          
          # Topic collection - collect all topics
          TOPIC_MODE: "all"
          TOPIC_LIST: '[]'
          TOPIC_REGEX: '[]'
          
          # Consumer offset collection
          CONSUMER_OFFSET: "true"
          CONSUMER_GROUPS: '[]'  # Empty means all groups
          
          # Enable all data types
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          
          # Timeouts and intervals
          TIMEOUT: "30000"
          CONNECTION_TIMEOUT: "30000"
          
          # Producer/Consumer collection
          COLLECT_BROKER_TOPIC_DATA: "true"
          PRODUCERS: '[]'  # Empty means all
          CONSUMERS: '[]'  # Empty means all
          
          # Verbose logging for debugging
          VERBOSE: "true"
          
        interval: 30s
        timeout: 30s
        inventory_source: config/kafka
        labels:
          env: kubernetes
          cluster: kafka-k8s-monitoring
          integration: nri-kafka