apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nri-kafka-daemonset
  namespace: strimzi-kafka  # Update this to your namespace
  labels:
    app: nri-kafka
spec:
  selector:
    matchLabels:
      app: nri-kafka
  template:
    metadata:
      labels:
        app: nri-kafka
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: newrelic
      containers:
      - name: nri-kafka
        image: newrelic/infrastructure:latest
        env:
        # New Relic License Key
        - name: NRIA_LICENSE_KEY
          value: "dfb79449d23acce4df582f2f5550abe4FFFFNRAL"
        
        # Cluster name
        - name: CLUSTER_NAME
          value: "kafka-k8s-monitoring"
        
        # Infrastructure settings
        - name: NRIA_OVERRIDE_HOSTNAME_SHORT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        
        - name: NRIA_CUSTOM_ATTRIBUTES
          value: '{"clusterName":"kafka-k8s-monitoring","environment":"kubernetes"}'
        
        # Enable verbose logging
        - name: NRIA_VERBOSE
          value: "1"
        - name: NRIA_LOG_LEVEL
          value: "debug"
        
        # Pass environment to integrations
        - name: NRIA_PASSTHROUGH_ENVIRONMENT
          value: "KUBERNETES_SERVICE_HOST,KUBERNETES_SERVICE_PORT,CLUSTER_NAME"
        
        volumeMounts:
        - name: config
          mountPath: /etc/newrelic-infra/integrations.d/
          readOnly: true
        - name: host-root
          mountPath: /host
          readOnly: true
        - name: log
          mountPath: /var/log/newrelic-infra
        
        resources:
          requests:
            memory: "150Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "200m"
        
        securityContext:
          privileged: true
          
      volumes:
      - name: config
        configMap:
          name: nri-kafka-config
      - name: host-root
        hostPath:
          path: /
      - name: log
        emptyDir: {}