apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-producer
  namespace: strimzi-kafka
  labels:
    app: kafka-test-producer
spec:
  containers:
  - name: producer
    image: strimzi/kafka:latest-kafka-3.3.1
    command:
    - /bin/bash
    - -c
    - |
      # Create topic if it doesn't exist
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server production-kafka-kafka-bootstrap:9092 \
        --create --if-not-exists --topic test-topic --partitions 3 --replication-factor 3 || true
      
      # Start producing messages
      echo "Starting producer..."
      i=0
      while true; do
        echo "Test message $i from producer at $(date)" | \
          /opt/kafka/bin/kafka-console-producer.sh \
          --bootstrap-server production-kafka-kafka-bootstrap:9092 \
          --topic test-topic
        ((i++))
        sleep 5
      done
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-consumer
  namespace: strimzi-kafka
  labels:
    app: kafka-test-consumer
spec:
  containers:
  - name: consumer
    image: strimzi/kafka:latest-kafka-3.3.1
    command:
    - /bin/bash
    - -c
    - |
      echo "Starting consumer..."
      /opt/kafka/bin/kafka-console-consumer.sh \
        --bootstrap-server production-kafka-kafka-bootstrap:9092 \
        --topic test-topic \
        --from-beginning \
        --group test-consumer-group \
        --consumer-property enable.auto.commit=true \
        --consumer-property auto.commit.interval.ms=1000
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-test-consumer-2
  namespace: strimzi-kafka
  labels:
    app: kafka-test-consumer
spec:
  containers:
  - name: consumer
    image: strimzi/kafka:latest-kafka-3.3.1
    command:
    - /bin/bash
    - -c
    - |
      echo "Starting consumer 2..."
      /opt/kafka/bin/kafka-console-consumer.sh \
        --bootstrap-server production-kafka-kafka-bootstrap:9092 \
        --topic test-topic \
        --group metrics-consumer-group \
        --consumer-property enable.auto.commit=true