apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-config-fixed
  namespace: strimzi-kafka
data:
  kafka-config.yml: |
    ---
    integrations:
      - name: nri-kafka
        env:
          # Fixed cluster name matching actual deployment
          CLUSTER_NAME: strimzi-production-kafka
          
          # Auto-discovery using bootstrap - more reliable
          AUTODISCOVER_STRATEGY: bootstrap
          
          # Bootstrap broker - correct Strimzi service
          BOOTSTRAP_BROKER_HOST: production-kafka-kafka-bootstrap.strimzi-kafka.svc.cluster.local
          BOOTSTRAP_BROKER_KAFKA_PORT: 9092
          BOOTSTRAP_BROKER_JMX_PORT: 9999
          
          # JMX settings - no auth for Strimzi
          DEFAULT_JMX_USER: ""
          DEFAULT_JMX_PASSWORD: ""
          JMX_USER: ""
          JMX_PASS: ""
          
          # CRITICAL FIX: Enable topic collection
          TOPIC_MODE: all
          COLLECT_TOPIC_SIZE: "true"
          COLLECT_TOPIC_OFFSET: "true"
          
          # CRITICAL FIX: Enable consumer offset monitoring
          CONSUMER_OFFSET: "true"
          INACTIVE_CONSUMER_GROUP_OFFSET: "true"
          CONSUMER_GROUP_OFFSET_BY_TOPIC: "true"
          
          # Force topic sample collection
          FORCE_TOPIC_SAMPLE_COLLECTION: "true"
          
          # Collect broker topic data
          COLLECT_BROKER_TOPIC_DATA: "true"
          
          # Enable all data types
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          
          # Connection settings
          TIMEOUT: "30000"
          CONNECTION_TIMEOUT: "30000"
          MAX_JMX_CONNECTIONS: "10"
          
          # Producer/Consumer JMX collection
          PRODUCERS: '[]'
          CONSUMERS: '[]'
          
          # Consumer group settings - collect all groups
          CONSUMER_GROUP_REGEX: ".*"
          
          # Preferred listener for internal connections
          PREFERRED_LISTENER: "PLAIN"
          
          # Verbose logging for debugging
          VERBOSE: "true"
          
        interval: 30s
        timeout: 30s
        inventory_source: config/kafka
        labels:
          env: kubernetes
          cluster: strimzi-production-kafka
          integration: nri-kafka