apiVersion: apps/v1
kind: Deployment
metadata:
  name: nri-kafka-msk-shim-fixed
  namespace: strimzi-kafka
  labels:
    app: nri-kafka-msk-shim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nri-kafka-msk-shim-fixed
  template:
    metadata:
      labels:
        app: nri-kafka-msk-shim-fixed
    spec:
      serviceAccountName: newrelic
      containers:
      - name: nri-kafka
        image: newrelic/nri-kafka:latest
        imagePullPolicy: Always
        env:
        # MSK Shim Configuration - MUST match cluster name in ConfigMap
        - name: MSK_SHIM_ENABLED
          value: "true"
        - name: AWS_ACCOUNT_ID
          value: "123456789012"
        - name: AWS_REGION
          value: "us-east-1"
        - name: KAFKA_CLUSTER_NAME
          value: "strimzi-production-kafka"
        - name: ENVIRONMENT
          value: "production"
        
        # New Relic License Key from .env
        - name: NRIA_LICENSE_KEY
          value: "dfb79449d23acce4df582f2f5550abe4FFFFNRAL"
        
        # Infrastructure Agent Settings
        - name: NRIA_OVERRIDE_HOSTNAME_SHORT
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        
        - name: NRIA_CUSTOM_ATTRIBUTES
          value: '{"clusterName":"strimzi-production-kafka","environment":"kubernetes","integration":"msk-shim","pipeline":"msk","msk":"true"}'
        
        # Enhanced logging
        - name: NRIA_LOG_LEVEL
          value: "debug"
        - name: NRIA_VERBOSE
          value: "1"
        
        # Pass through environment variables
        - name: NRIA_PASSTHROUGH_ENVIRONMENT
          value: "KUBERNETES_SERVICE_HOST,KUBERNETES_SERVICE_PORT,MSK_SHIM_ENABLED,AWS_ACCOUNT_ID,AWS_REGION,KAFKA_CLUSTER_NAME,ENVIRONMENT"
        
        volumeMounts:
        - name: config
          mountPath: /etc/newrelic-infra/integrations.d/
          readOnly: true
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
            
      volumes:
      - name: config
        configMap:
          name: nri-kafka-config-fixed
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: newrelic
  namespace: strimzi-kafka
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: newrelic
rules:
- apiGroups: [""]
  resources:
    - nodes
    - nodes/metrics
    - nodes/stats
    - nodes/proxy
    - pods
    - services
    - endpoints
  verbs: ["get", "list"]
- apiGroups: ["kafka.strimzi.io"]
  resources:
    - kafkas
    - kafkatopics
    - kafkausers
  verbs: ["get", "list"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: newrelic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: newrelic
subjects:
- kind: ServiceAccount
  name: newrelic
  namespace: strimzi-kafka