# Polaris configuration for Kubernetes security validation

checks:
  # Security
  runAsNonRoot: warning
  runAsUser: warning
  readOnlyRootFilesystem: warning
  allowPrivilegeEscalation: danger
  
  # Efficiency
  cpuRequestsMissing: warning
  cpuLimitsMissing: warning
  memoryRequestsMissing: warning
  memoryLimitsMissing: warning
  
  # Reliability
  deploymentMissingReplicas: warning
  priorityClassNotSet: ignore
  tagNotSpecified: danger
  pullPolicyNotAlways: ignore
  
  # Images
  imageRegistry: ignore
  imagePullPolicyMissing: warning
  
  # Networking
  hostNetworkSet: danger
  hostPortSet: warning
  
  # Storage
  hostPathVolumePresent: danger
  
  # Health checks
  readinessProbeMissing: warning
  livenessProbeMissing: warning

exemptions:
  - namespace: kube-system
  - namespace: kube-public
  - namespace: kube-node-lease

mutations: []