apiVersion: v2
name: message-queues-platform
description: A Helm chart for New Relic Message Queues Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - newrelic
  - monitoring
  - message-queues
  - kafka
  - observability
home: https://github.com/your-org/newrelic-message-queues-platform
maintainers:
  - name: New Relic Community
    email: community@newrelic.com