from pathlib import Path
import networkx as nx
import pandas as pd
from microlink.utils.log import get_logger
LOG = get_logger(__name__)

def main(G: nx.MultiDiGraph, order_id: str, demo: bool = False) -> Path:
    sub = [e for e in G.edges if order_id in e]
    H = nx.edge_subgraph(G, sub)
    
    # Instead of using PyVis, we'll create a simple HTML visualization
    nodes_data = []
    for n, d in H.nodes(data=True):
        label = n if d["type"] == "DataInstance" else n.split("_")[1]
        nodes_data.append({"id": n, "label": label, "type": d["type"]})
    
    edges_data = []
    for u, v, d in H.edges(data=True):
        edges_data.append({"from": u, "to": v, "label": d.get("rel", "")})
    
    # Create a simple HTML file
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>MicroLink Flow: {order_id}</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; }}
            h1 {{ color: #333; }}
            table {{ border-collapse: collapse; width: 100%; margin-bottom: 20px; }}
            th, td {{ text-align: left; padding: 8px; border: 1px solid #ddd; }}
            th {{ background-color: #f2f2f2; }}
            tr:nth-child(even) {{ background-color: #f9f9f9; }}
        </style>
    </head>
    <body>
        <h1>MicroLink Flow for {order_id}</h1>
        
        <h2>Nodes</h2>
        <table>
            <tr>
                <th>ID</th>
                <th>Label</th>
                <th>Type</th>
            </tr>
            {"".join(f"<tr><td>{n['id']}</td><td>{n['label']}</td><td>{n['type']}</td></tr>" for n in nodes_data)}
        </table>
        
        <h2>Edges</h2>
        <table>
            <tr>
                <th>From</th>
                <th>To</th>
                <th>Relationship</th>
            </tr>
            {"".join(f"<tr><td>{e['from']}</td><td>{e['to']}</td><td>{e['label']}</td></tr>" for e in edges_data)}
        </table>
        
        <p><strong>Generated by MicroLink</strong></p>
    </body>
    </html>
    """
    
    # Write to file
    out = Path("output") / f"{order_id}.html"
    with open(out, "w") as f:
        f.write(html_content)
    
    LOG.info("rendered %s", out)
    return out
