apiVersion: v1
kind: Service
metadata:
  name: mq-platform
  namespace: message-queues-platform
  labels:
    app: message-queues-platform
    component: platform
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: health
    protocol: TCP
    name: health
  selector:
    app: message-queues-platform
    component: platform
---
# Optional: Expose health check endpoint externally
apiVersion: v1
kind: Service
metadata:
  name: mq-platform-nodeport
  namespace: message-queues-platform
  labels:
    app: message-queues-platform
    component: platform
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: health
    nodePort: 30001
    protocol: TCP
    name: health
  selector:
    app: message-queues-platform
    component: platform