apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
spec:
  clusterIP: None
  ports:
  - name: broker
    port: 9092
  - name: jmx
    port: 9999
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  ports:
  - name: broker
    port: 9092
  - name: jmx
    port: 9999
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  ports:
  - port: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.8
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        component: broker
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:3.5.1
        ports:
        - containerPort: 9092
          name: broker
        - containerPort: 9999
          name: jmx
        env:
        - name: KAFKA_CFG_BROKER_ID
          value: "0"
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-0.kafka-headless.kafka.svc.cluster.local:9092
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: JMX_PORT
          value: "9999"
        - name: KAFKA_JMX_OPTS
          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=kafka-0.kafka-headless.kafka.svc.cluster.local"
---
# Sidecar deployment for nri-kafka
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-with-nri-sidecar
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-sidecar
  template:
    metadata:
      labels:
        app: kafka-sidecar
        component: broker
    spec:
      containers:
      # Kafka container
      - name: kafka
        image: bitnami/kafka:3.5.1
        ports:
        - containerPort: 9092
          name: broker
        - containerPort: 9999
          name: jmx
        env:
        - name: KAFKA_CFG_BROKER_ID
          value: "100"
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-sidecar.kafka.svc.cluster.local:9092
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: JMX_PORT
          value: "9999"
        - name: KAFKA_JMX_OPTS
          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=localhost"
      
      # NRI-Kafka sidecar
      - name: nri-kafka
        image: newrelic/infrastructure-bundle:3.2.71
        env:
        - name: NRIA_LICENSE_KEY
          value: "dfb79449d23acce4df582f2f5550abe4FFFFNRAL"
        - name: NRIA_VERBOSE
          value: "1"
        - name: CLUSTER_NAME
          value: "k8s-kafka-cluster"
        volumeMounts:
        - name: config
          mountPath: /etc/newrelic-infra/integrations.d/
      volumes:
      - name: config
        configMap:
          name: kafka-sidecar-config
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-sidecar
  namespace: kafka
spec:
  ports:
  - name: broker
    port: 9092
  - name: jmx
    port: 9999
  selector:
    app: kafka-sidecar
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-sidecar-config
  namespace: kafka
data:
  nri-kafka-config.yml: |
    integrations:
      - name: nri-kafka
        command: nri-kafka
        env:
          CLUSTER_NAME: k8s-kafka-cluster
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: localhost
          BOOTSTRAP_BROKER_JMX_PORT: "9999"
          BOOTSTRAP_BROKER_KAFKA_PORT: "9092"
          BOOTSTRAP_BROKER_KAFKA_PROTOCOL: PLAINTEXT
          DEFAULT_JMX_USER: ""
          DEFAULT_JMX_PASSWORD: ""
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          CONSUMER_OFFSET: "true"
          TOPIC_MODE: all
          VERBOSE: "true"
        interval: 30s
        labels:
          env: kubernetes
          role: kafka-broker-sidecar