apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-exporter-config
  namespace: kafka
data:
  jmx-kafka-prometheus.yml: |
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:9999/jmxrmi
    ssl: false
    lowercaseOutputName: false
    lowercaseOutputLabelNames: false
    whitelistObjectNames:
    - kafka.server:type=BrokerTopicMetrics,*
    - kafka.server:type=ReplicaManager,*
    - kafka.controller:type=*,*
    - kafka.network:type=RequestMetrics,*
    - kafka.server:type=KafkaRequestHandlerPool,*
    - kafka.server:type=DelayedOperationPurgatory,*
    - kafka.log:type=LogFlushStats,*
    rules:
    - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
       clientId: "$3"
       topic: "$4"
       partition: "$5"
    - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
       clientId: "$3"
       broker: "$4:$5"
    - pattern: kafka.server<type=(.+), name=(.+)><>OneMinuteRate
      name: kafka_server_$1_$2_one_minute_rate
      type: GAUGE
    - pattern: kafka.server<type=(.+), name=(.+)><>Count
      name: kafka_server_$1_$2_total
      type: COUNTER
    - pattern: kafka.server<type=(.+), name=(.+), topic=(.+)><>Count
      name: kafka_server_$1_$2_total
      type: COUNTER
      labels:
        topic: "$3"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-jmx-metrics
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
  - name: metrics
    port: 5556
    targetPort: 5556
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-jmx-exporter
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-jmx-exporter
  template:
    metadata:
      labels:
        app: kafka-jmx-exporter
    spec:
      containers:
      - name: jmx-exporter
        image: bitnami/jmx-exporter:0.19.0
        ports:
        - containerPort: 5556
          name: metrics
        args:
        - "5556"
        - "/etc/jmx-exporter/jmx-kafka-prometheus.yml"
        volumeMounts:
        - name: config
          mountPath: /etc/jmx-exporter
        env:
        - name: JMX_URL
          value: "service:jmx:rmi:///jndi/rmi://kafka.kafka.svc.cluster.local:9999/jmxrmi"
      volumes:
      - name: config
        configMap:
          name: kafka-jmx-exporter-config