apiVersion: v1
kind: Namespace
metadata:
  name: kafka-clients
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafka-clients
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: producer
        image: bitnami/kafka:3.5.1
        command:
        - /bin/bash
        - -c
        - |
          while true; do
            echo "Message at $(date)" | /opt/bitnami/kafka/bin/kafka-console-producer.sh \
              --broker-list kafka.kafka.svc.cluster.local:9092 \
              --topic test-topic || true
            sleep 5
          done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: kafka-clients
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: consumer
        image: bitnami/kafka:3.5.1
        command:
        - /bin/bash
        - -c
        - |
          /opt/bitnami/kafka/bin/kafka-console-consumer.sh \
            --bootstrap-server kafka.kafka.svc.cluster.local:9092 \
            --topic test-topic \
            --from-beginning