apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-standalone-config
  namespace: newrelic
data:
  nri-kafka-config.yml: |
    integrations:
      - name: nri-kafka
        command: nri-kafka
        arguments:
          cluster_name: k8s-kafka-cluster
          autodiscover_strategy: bootstrap
          bootstrap_broker_host: kafka.kafka.svc.cluster.local
          bootstrap_broker_jmx_port: "9999"
          bootstrap_broker_kafka_port: "9092"
          bootstrap_broker_kafka_protocol: PLAINTEXT
          # Disable JMX authentication
          default_jmx_user: ""
          default_jmx_password: ""
          # Collection settings
          metrics: true
          inventory: true
          events: true
          consumer_offset: true
          # Topic settings
          topic_mode: all
          # Logging
          verbose: true
        labels:
          env: kubernetes
          role: kafka-monitor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nri-kafka-standalone
  namespace: newrelic
spec:
  selector:
    matchLabels:
      app: nri-kafka-standalone
  template:
    metadata:
      labels:
        app: nri-kafka-standalone
    spec:
      serviceAccountName: nri-bundle-newrelic-infrastructure
      hostNetwork: false
      containers:
      - name: nri-kafka
        image: newrelic/infrastructure-bundle:3.2.71
        env:
        - name: NRIA_LICENSE_KEY
          value: "dfb79449d23acce4df582f2f5550abe4FFFFNRAL"
        - name: NRIA_VERBOSE
          value: "1"
        - name: CLUSTER_NAME
          value: "k8s-kafka-cluster"
        - name: NRIA_PASSTHROUGH_ENVIRONMENT
          value: "CLUSTER_NAME,NRIA_LICENSE_KEY"
        - name: NRIA_CUSTOM_ATTRIBUTES
          value: '{"clusterName":"k8s-kafka-cluster","integration":"kafka","deployment":"standalone"}'
        volumeMounts:
        - name: config
          mountPath: /etc/newrelic-infra/integrations.d/
        - name: host-root
          mountPath: /host
          readOnly: true
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 150Mi
      volumes:
      - name: config
        configMap:
          name: nri-kafka-standalone-config
      - name: host-root
        hostPath:
          path: /