---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-debug-config
  namespace: kafka
data:
  # Test 1: Minimal bootstrap configuration with debug logging
  bootstrap-debug.yml: |
    integrations:
      - name: nri-kafka
        command: nri-kafka
        env:
          CLUSTER_NAME: k8s-kafka-debug
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: kafka-0.kafka-headless.kafka.svc.cluster.local
          BOOTSTRAP_BROKER_JMX_PORT: "9999"
          BOOTSTRAP_BROKER_KAFKA_PORT: "9092"
          
          # Version settings - try different versions
          KAFKA_VERSION: "3.5.0"  # Match Bitnami Kafka version
          
          # Metrics collection
          METRICS: "true"
          INVENTORY: "false"
          EVENTS: "false"
          
          # Disable topic/consumer collection initially
          TOPIC_MODE: "none"
          CONSUMER_OFFSET: "false"
          
          # Timeouts and limits
          TIMEOUT: "60000"
          MAX_JMX_CONNECTIONS: "1"
          
          # Debug logging
          VERBOSE: "true"
          LOG_LEVEL: "debug"
          NRI_LOG_LEVEL: "debug"
          NRJMX_VERBOSE: "true"
          
        interval: 60s
        labels:
          test: bootstrap-debug

  # Test 2: JMX Only - No autodiscovery
  jmx-only-debug.yml: |
    integrations:
      - name: nri-kafka
        command: nri-kafka
        env:
          CLUSTER_NAME: k8s-kafka-jmx-only
          
          # Direct broker configuration
          BROKERS: '[{"host": "kafka-0.kafka-headless.kafka.svc.cluster.local", "port": 9092, "jmx_port": 9999}]'
          
          # Collection settings
          METRICS: "true"
          INVENTORY: "false"
          EVENTS: "false"
          LOCAL_ONLY_COLLECTION: "true"
          
          # No topic/consumer collection
          TOPIC_MODE: "none"
          CONSUMER_OFFSET: "false"
          
          # Kafka version
          KAFKA_VERSION: "3.5.0"
          
          # Debug
          VERBOSE: "true"
          LOG_LEVEL: "trace"
          
        interval: 60s
        labels:
          test: jmx-only-debug

  # Test 3: Localhost connection (for sidecar)
  localhost-debug.yml: |
    integrations:
      - name: nri-kafka
        command: nri-kafka
        env:
          CLUSTER_NAME: k8s-kafka-localhost
          
          # Localhost configuration
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: localhost
          BOOTSTRAP_BROKER_JMX_PORT: "9999"
          BOOTSTRAP_BROKER_KAFKA_PORT: "9092"
          
          # Basic metrics only
          METRICS: "true"
          INVENTORY: "false"
          EVENTS: "false"
          LOCAL_ONLY_COLLECTION: "true"
          
          # No topics
          TOPIC_MODE: "none"
          CONSUMER_OFFSET: "false"
          
          # Version
          KAFKA_VERSION: "3.5.0"
          
          # Debug
          VERBOSE: "true"
          LOG_LEVEL: "debug"
          
        interval: 60s
        labels:
          test: localhost-debug

---
apiVersion: v1
kind: Pod
metadata:
  name: nri-kafka-debug
  namespace: kafka
  labels:
    app: nri-kafka-debug
spec:
  containers:
  - name: debug
    image: newrelic/infrastructure-bundle:3.2.71
    env:
    - name: NRIA_LICENSE_KEY
      value: "dfb79449d23acce4df582f2f5550abe4FFFFNRAL"
    - name: NRIA_VERBOSE
      value: "3"  # Maximum verbosity
    - name: NRIA_LOG_LEVEL
      value: "trace"
    - name: NRI_LOG_LEVEL
      value: "trace"
    command: ["/bin/sh", "-c"]
    args:
    - |
      echo "=== Starting nri-kafka debug tests ==="
      
      # Test 1: Bootstrap discovery
      echo -e "\n\n=== TEST 1: Bootstrap Discovery ==="
      /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka \
        --cluster_name test1 \
        --autodiscover_strategy bootstrap \
        --bootstrap_broker_host kafka-0.kafka-headless.kafka.svc.cluster.local \
        --bootstrap_broker_jmx_port 9999 \
        --bootstrap_broker_kafka_port 9092 \
        --kafka_version 3.5.0 \
        --metrics \
        --verbose \
        --pretty 2>&1 | tee /tmp/test1.log
      
      # Test 2: Direct broker list
      echo -e "\n\n=== TEST 2: Direct Broker List ==="
      /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka \
        --cluster_name test2 \
        --brokers '[{"host": "kafka-0.kafka-headless.kafka.svc.cluster.local", "port": 9092, "jmx_port": 9999}]' \
        --kafka_version 3.5.0 \
        --metrics \
        --local_only_collection \
        --verbose \
        --pretty 2>&1 | tee /tmp/test2.log
      
      # Test 3: Different Kafka versions
      for version in "1.0.0" "2.8.0" "3.0.0" "3.5.0"; do
        echo -e "\n\n=== TEST 3: Kafka Version $version ==="
        /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka \
          --cluster_name "test3-v$version" \
          --bootstrap_broker_host kafka-0.kafka-headless.kafka.svc.cluster.local \
          --bootstrap_broker_jmx_port 9999 \
          --bootstrap_broker_kafka_port 9092 \
          --kafka_version "$version" \
          --metrics \
          --topic_mode none \
          --consumer_offset false \
          --verbose \
          --pretty 2>&1 | tee "/tmp/test3-v$version.log"
      done
      
      # Test 4: JMX query test
      echo -e "\n\n=== TEST 4: Raw JMX Query ==="
      export LOG_LEVEL=trace
      export NRI_LOG_LEVEL=trace
      export NRJMX_VERBOSE=true
      
      /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka \
        --cluster_name test4 \
        --bootstrap_broker_host kafka-0.kafka-headless.kafka.svc.cluster.local \
        --bootstrap_broker_jmx_port 9999 \
        --bootstrap_broker_kafka_port 9092 \
        --metrics \
        --timeout 120000 \
        --pretty 2>&1 | tee /tmp/test4.log
      
      # Keep pod running to examine logs
      echo -e "\n\n=== Debug tests complete. Keeping pod alive for log examination ==="
      echo "Check logs in /tmp/test*.log"
      sleep 3600
    volumeMounts:
    - name: config
      mountPath: /etc/newrelic-infra/integrations.d/
  volumes:
  - name: config
    configMap:
      name: nri-kafka-debug-config
---
# Sidecar debug deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-debug-sidecar
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-debug-sidecar
  template:
    metadata:
      labels:
        app: kafka-debug-sidecar
    spec:
      containers:
      # Kafka container
      - name: kafka
        image: bitnami/kafka:3.5.1
        ports:
        - containerPort: 9092
        - containerPort: 9999
        env:
        - name: KAFKA_CFG_BROKER_ID
          value: "300"
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-debug-sidecar.kafka.svc.cluster.local:9092
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: JMX_PORT
          value: "9999"
        - name: KAFKA_JMX_OPTS
          value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=localhost"
      
      # Debug sidecar
      - name: debug
        image: newrelic/infrastructure-bundle:3.2.71
        env:
        - name: NRIA_LICENSE_KEY
          value: "dfb79449d23acce4df582f2f5550abe4FFFFNRAL"
        - name: NRIA_VERBOSE
          value: "3"
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Wait for Kafka to start
          sleep 30
          
          echo "Testing localhost connection from sidecar..."
          
          # Test with trace logging
          export LOG_LEVEL=trace
          export NRI_LOG_LEVEL=trace
          export NRJMX_VERBOSE=true
          
          /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka \
            --cluster_name sidecar-test \
            --bootstrap_broker_host localhost \
            --bootstrap_broker_jmx_port 9999 \
            --bootstrap_broker_kafka_port 9092 \
            --kafka_version 3.5.0 \
            --metrics \
            --local_only_collection \
            --topic_mode none \
            --consumer_offset false \
            --verbose \
            --pretty 2>&1 | tee /tmp/sidecar-debug.log
          
          # Also test with minimal config
          echo -e "\n\nMinimal config test..."
          /var/db/newrelic-infra/newrelic-integrations/bin/nri-kafka \
            --cluster_name minimal \
            --jmx_host localhost \
            --jmx_port 9999 \
            --metrics \
            --pretty 2>&1 | tee /tmp/minimal-debug.log
          
          echo "Debug complete. Check /tmp/*.log"
          sleep 3600
        volumeMounts:
        - name: localhost-config
          mountPath: /etc/newrelic-infra/integrations.d/
      volumes:
      - name: localhost-config
        configMap:
          name: nri-kafka-debug-config
          items:
          - key: localhost-debug.yml
            path: nri-kafka-config.yml