apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-config
  namespace: newrelic
data:
  nri-kafka-config.yml: |
    integrations:
      - name: nri-kafka
        command: nri-kafka
        env:
          CLUSTER_NAME: k8s-kafka-cluster
          AUTODISCOVER_STRATEGY: bootstrap
          
          # Use the headless service DNS names for each broker
          BOOTSTRAP_BROKER_HOST: kafka-0.kafka-headless.kafka.svc.cluster.local
          BOOTSTRAP_BROKER_JMX_PORT: "9999"
          BOOTSTRAP_BROKER_KAFKA_PORT: "9092"
          BOOTSTRAP_BROKER_KAFKA_PROTOCOL: PLAINTEXT
          
          # JMX settings
          JMX_HOST: ""  # Empty to use bootstrap broker host
          JMX_PORT: ""  # Empty to use bootstrap broker JMX port
          JMX_USER: ""
          JMX_PASSWORD: ""
          
          # Collection settings
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          
          # Consumer settings
          CONSUMER_OFFSET: "true"
          CONSUMER_GROUP_REGEX: ".*"
          
          # Topic settings
          TOPIC_MODE: all
          TOPIC_REGEX: ".*"
          COLLECT_TOPIC_SIZE: "true"
          COLLECT_TOPIC_OFFSET: "true"
          
          # Logging
          VERBOSE: "true"
          NRJMX_VERBOSE: "true"
        interval: 30s
        labels:
          env: kubernetes
          cluster: kafka
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nri-kafka-monitor
  namespace: newrelic
spec:
  selector:
    matchLabels:
      app: nri-kafka-monitor
  template:
    metadata:
      labels:
        app: nri-kafka-monitor
    spec:
      serviceAccountName: nri-bundle-newrelic-infrastructure
      containers:
      - name: nri-kafka
        image: newrelic/infrastructure:latest
        env:
        - name: NRIA_LICENSE_KEY
          value: "dfb79449d23acce4df582f2f5550abe4FFFFNRAL"
        - name: NRIA_VERBOSE
          value: "1"
        - name: NRIA_LOG_LEVEL
          value: "debug"
        - name: NRIA_CUSTOM_ATTRIBUTES
          value: |
            {"clusterName":"k8s-kafka-cluster","integration":"kafka","deployment":"statefulset"}
        volumeMounts:
        - name: nri-kafka-config
          mountPath: /etc/newrelic-infra/integrations.d/
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 150Mi
      volumes:
      - name: nri-kafka-config
        configMap:
          name: nri-kafka-config
