apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-working-config
  namespace: newrelic
data:
  nri-kafka-config.yml: |
    integrations:
      - name: nri-kafka
        command: nri-kafka
        arguments:
          cluster_name: k8s-kafka-cluster
          autodiscover_strategy: bootstrap
          bootstrap_broker_host: kafka-broker.kafka.svc.cluster.local
          bootstrap_broker_kafka_port: "9092"
          bootstrap_broker_kafka_protocol: PLAINTEXT
          # Disable JMX collection - focus on Kafka protocol metrics
          metrics: false
          inventory: false
          events: false
          # Enable consumer offset collection only
          consumer_offset: true
          consumer_group_regex: ".*"
          # Topic collection
          topic_mode: all
          collect_topic_size: true
        labels:
          env: kubernetes
          role: kafka-consumer-offset-monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nri-kafka-consumer-offset
  namespace: newrelic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nri-kafka-consumer-offset
  template:
    metadata:
      labels:
        app: nri-kafka-consumer-offset
    spec:
      serviceAccountName: nri-bundle-newrelic-infrastructure
      containers:
      - name: nri-kafka
        image: newrelic/infrastructure-bundle:3.2.71
        env:
        - name: NRIA_LICENSE_KEY
          value: "dfb79449d23acce4df582f2f5550abe4FFFFNRAL"
        - name: NRIA_VERBOSE
          value: "1"
        - name: CLUSTER_NAME
          value: "k8s-kafka-cluster"
        - name: NRIA_CUSTOM_ATTRIBUTES
          value: '{"clusterName":"k8s-kafka-cluster","integration":"kafka-consumer-offset"}'
        volumeMounts:
        - name: config
          mountPath: /etc/newrelic-infra/integrations.d/
        resources:
          limits:
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 150Mi
      volumes:
      - name: config
        configMap:
          name: nri-kafka-working-config