apiVersion: v1
kind: ConfigMap
metadata:
  name: nri-kafka-config
  namespace: newrelic
data:
  # JMX connection settings for secure environments
  jmx-config.yml: |
    # JMX SSL Configuration (if needed)
    jmx_ssl_enabled: false
    jmx_ssl_truststore_path: /etc/ssl/kafka/truststore.jks
    jmx_ssl_truststore_password: changeit
    jmx_ssl_keystore_path: /etc/ssl/kafka/keystore.jks
    jmx_ssl_keystore_password: changeit
    
  # Kafka SASL configuration (if needed)
  sasl-config.yml: |
    # SASL Configuration
    sasl_mechanism: PLAIN
    sasl_username: admin
    sasl_password: admin-secret
    
  # Topic filters and monitoring configuration
  monitoring-config.yml: |
    # Topic monitoring configuration
    topic_mode: all
    # Alternatively, use regex mode:
    # topic_mode: regex
    # topic_regex: '^(events|transactions|logs).*'
    
    # Consumer group monitoring
    consumer_group_regex: '.*'
    
    # Collection intervals (in seconds)
    metrics_collection_interval: 30
    inventory_collection_interval: 60
    
  # Custom metric mappings
  metric-mappings.yml: |
    # Custom metric name mappings
    metric_mappings:
      - source: kafka.broker:type=BrokerTopicMetrics,name=MessagesInPerSec
        target: kafka.broker.messages.in.rate
      - source: kafka.broker:type=BrokerTopicMetrics,name=BytesInPerSec
        target: kafka.broker.bytes.in.rate
      - source: kafka.broker:type=BrokerTopicMetrics,name=BytesOutPerSec
        target: kafka.broker.bytes.out.rate