global:
  licenseKey: dfb79449d23acce4df582f2f5550abe4FFFFNRAL
  cluster: k8s-kafka-cluster
  lowDataMode: false

nri-metadata-injection:
  enabled: true

kube-state-metrics:
  enabled: true

nri-prometheus:
  enabled: true

newrelic-infrastructure:
  enabled: true
  
  common:
    integrations:
      # Simple Kafka integration without discovery
      - name: nri-kafka
        interval: 30s
        env:
          CLUSTER_NAME: k8s-kafka-cluster
          AUTODISCOVER_STRATEGY: bootstrap
          BOOTSTRAP_BROKER_HOST: kafka.kafka.svc.cluster.local
          BOOTSTRAP_BROKER_JMX_PORT: "9999"
          BOOTSTRAP_BROKER_KAFKA_PORT: "9092"
          BOOTSTRAP_BROKER_KAFKA_PROTOCOL: PLAINTEXT
          METRICS: "true"
          INVENTORY: "true"
          EVENTS: "true"
          CONSUMER_OFFSET: "true"
          TOPIC_MODE: all

# Logging configuration
logging:
  enabled: true
  
# Privilege mode may be needed for some integrations
privileged: true