# New Relic Infrastructure Bundle values for nri-kafka integration with Strimzi
# This file configures the nri-bundle Helm chart to monitor Strimzi-deployed Kafka

global:
  licenseKey: YOUR_NEW_RELIC_LICENSE_KEY
  cluster: YOUR_CLUSTER_NAME
  lowDataMode: false

nri-metadata-injection:
  enabled: true

kube-state-metrics:
  enabled: true

nri-prometheus:
  enabled: true

newrelic-infrastructure:
  enabled: true
  # Configure resource limits
  resources:
    limits:
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 150Mi
  
  # Custom integrations for nri-kafka with Strimzi
  integrations:
    # Kafka Broker Monitoring Configuration for Strimzi
    kafka-broker.yaml: |
      discovery:
        command:
          exec: /var/db/newrelic-infra/nri-discovery-kubernetes --port 10250 --tls
          match:
            label.strimzi.io/cluster: my-cluster
            label.strimzi.io/kind: Kafka
            label.strimzi.io/name: my-cluster-kafka
      integrations:
        - name: nri-kafka
          env:
            CLUSTER_NAME: ${CLUSTER_NAME}
            AUTODISCOVER_STRATEGY: bootstrap
            # Strimzi uses a different naming pattern
            BOOTSTRAP_BROKER_HOST: ${discovery.podName}.${discovery.namespace}.svc.cluster.local
            BOOTSTRAP_BROKER_JMX_PORT: "9999"
            BOOTSTRAP_BROKER_KAFKA_PORT: "9092"
            BOOTSTRAP_BROKER_KAFKA_PROTOCOL: PLAINTEXT
            # JMX Authentication for Strimzi
            JMX_USER: ${discovery.podName}
            JMX_PASS_FROM_SECRET: kafka-jmx-secret
            # Collection settings
            METRICS: "true"
            INVENTORY: "true"
            LOCAL_ONLY_COLLECTION: "true"
            # Topic configuration
            TOPIC_MODE: all
    
    # Consumer Offset Monitoring Configuration
    kafka-offset.yaml: |
      discovery:
        command:
          exec: /var/db/newrelic-infra/nri-discovery-kubernetes --port 10250 --tls
          match:
            label.strimzi.io/cluster: my-cluster
            label.strimzi.io/kind: Kafka
            label.strimzi.io/name: my-cluster-kafka
      integrations:
        - name: nri-kafka
          env:
            CLUSTER_NAME: ${CLUSTER_NAME}
            AUTODISCOVER_STRATEGY: bootstrap
            BOOTSTRAP_BROKER_HOST: my-cluster-kafka-bootstrap.${discovery.namespace}.svc.cluster.local
            BOOTSTRAP_BROKER_KAFKA_PORT: "9092"
            BOOTSTRAP_BROKER_KAFKA_PROTOCOL: PLAINTEXT
            # Only collect consumer offset metrics
            METRICS: "false"
            INVENTORY: "false"
            CONSUMER_OFFSET: "true"
            # Match all consumer groups
            CONSUMER_GROUP_REGEX: '.*'
    
    # Zookeeper Monitoring (if using Strimzi with ZooKeeper)
    zookeeper.yaml: |
      discovery:
        command:
          exec: /var/db/newrelic-infra/nri-discovery-kubernetes --port 10250 --tls
          match:
            label.strimzi.io/cluster: my-cluster
            label.strimzi.io/kind: Kafka
            label.strimzi.io/name: my-cluster-zookeeper
      integrations:
        - name: nri-kafka
          env:
            CLUSTER_NAME: ${CLUSTER_NAME}
            ZOOKEEPER_HOSTS: '[{"host": "${discovery.ip}", "port": 2181}]'
            METRICS: "true"
            INVENTORY: "true"

# Logging configuration
logging:
  enabled: true
  
# Privilege mode may be needed for some integrations
privileged: true