global:
  licenseKey: dfb79449d23acce4df582f2f5550abe4FFFFNRAL
  cluster: k8s-kafka-cluster
  lowDataMode: false

nri-metadata-injection:
  enabled: true

kube-state-metrics:
  enabled: true

nri-prometheus:
  enabled: true

newrelic-infrastructure:
  enabled: true
  
  # Enable verbose logging
  verboseLog: true
  
  # Common settings for all infrastructure components
  common:
    agentConfig:
      # Enable feature flags for custom integrations
      features:
        docker_enabled: true
      # Custom attributes
      custom_attributes:
        cluster_name: k8s-kafka-cluster
        environment: development
    
    # Define integrations at the common level
    integrations:
      nri-kafka-config.yml: |
        integrations:
          - name: nri-kafka
            env:
              CLUSTER_NAME: k8s-kafka-cluster
              AUTODISCOVER_STRATEGY: bootstrap
              BOOTSTRAP_BROKER_HOST: kafka.kafka.svc.cluster.local
              BOOTSTRAP_BROKER_JMX_PORT: "9999"
              BOOTSTRAP_BROKER_KAFKA_PORT: "9092"
              BOOTSTRAP_BROKER_KAFKA_PROTOCOL: PLAINTEXT
              JMX_SSL_ENABLE: "false"
              METRICS: "true"
              INVENTORY: "true"
              EVENTS: "true"
              CONSUMER_OFFSET: "true"
              TOPIC_MODE: all
              NRI_LOG_LEVEL: debug
            interval: 30s
            labels:
              env: kubernetes
              integration: kafka
            inventory_source: config/kafka

  # Resource limits per component
  ksm:
    resources:
      limits:
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 150Mi
        
  controlPlane:
    resources:
      limits:
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 150Mi
    
  kubelet:
    resources:
      limits:
        memory: 300Mi
      requests:
        cpu: 100m
        memory: 150Mi
    
    # Additional volume mounts for kubelet (where integrations run)
    extraVolumes:
      - name: nri-kafka-config
        configMap:
          name: nri-kafka-config
          items:
            - key: nri-kafka-config.yml
              path: nri-kafka-custom.yml
    
    extraVolumeMounts:
      - name: nri-kafka-config
        mountPath: /var/db/newrelic-infra/integrations.d/
        readOnly: true

# Logging configuration
logging:
  enabled: true
  
# Privilege mode for container runtime socket access
privileged: true